### ISSUE TITLE
Clicking the plus icon + should not collapse the container when adding a new tab

### ISSUE THREAD

**Issue by grahamperrin** [jonathanKingston/sea-containers#15]
1. click the name of a container
2. in the expanded view, observe the list of titles
3. click :heavy_plus_sign: 

## Expected

`4.` at the foot of the list, _New tab_

## Actual result

`4.` disappearance of the list (collapse of the container)

**Comment by bhearsum** [comment]
Has this been released yet? I'm running 0.8, and I still experience this.

**Comment by capsudo** [comment]
No still not released (not in 0.8). Is is fixed however in master (you need to install this extension from repo as debugging extension).
