### ISSUE TITLE
Buttons on Mac don't show

### ISSUE THREAD

**Issue by wagnerand** [jonathanKingston/sea-containers#19]
Somehow, the buttons on Mac are invisible (but working if you know where to click).

![screen shot 2017-06-02 at 18 12 49](https://cloud.githubusercontent.com/assets/873258/26734671/6b8a0b48-47ae-11e7-96d2-7bb0bdf90def.png)

(Same goes for the *Close* button on a tab).

**Comment by jonathanKingston** [comment]
@wagnerand thanks for raising. I should check Windows also!

I think the paths I am using are not in other themes perhaps. I should probably not hard-code them like this really.

**Comment by jonathanKingston** [comment]
New tab works, close doesn't in Windows.

**Comment by jonathanKingston** [comment]
Thanks for the report. It's now in add-on review stage.
