### ISSUE TITLE
Clicking on the + icon should not collapse the corresponding container

### ISSUE THREAD

**Issue by wagnerand** [jonathanKingston/sea-containers#24]
STR:
1. Have several containers.
2. Expand one of them.
3. Click the + icon for the one you just expanded.

Expected results:
The container does not collapse.

Actual results:
The container collapses.

**Comment by jonathanKingston** [comment]
This seems like a duplicate of #15 is that not the case? I agree this is a bug. Clicking the + button twice shouldn't do anything other than have two new tabs.

**Comment by wagnerand** [comment]
Ah yeah, seems like a dupe. Sorry.

**Comment by jonathanKingston** [comment]
No worries thanks!
