### ISSUE TITLE
Can't pin tabs from within the sidebar

### ISSUE THREAD

**Issue by Smile4ever** [jonathanKingston/sea-containers#25]
I cannot pin tabs using the tab context menu item in the sidebar.

**Comment by jonathanKingston** [comment]
You mentioned on IRC other context menu items missing... there is a pin tab option when right clicking on a tab. Is this not the case?

**Comment by Smile4ever** [comment]
Can't seem to reproduce this anymore, I will get back to you if I can.

Original issue:
There is a pin option, but it doesn't work for me. If I click it, it does nothing and I get a console error. (If I can reproduce the issue, I will add the detailed console error)
