### ISSUE TITLE
Add "move to different container" ability

### ISSUE THREAD

**Issue by tosascott** [jonathanKingston/sea-containers#35]
Very promising add-on. It's not Tab Groups, but I don't need Tab Groups. What I do need is to manage mental context & flow and this is a nice step in the right direction. (Not surprisingly, I'm a fan of the enhancement requests that would show _only_ the tabs in the current container -- _out of sight and out of mind_ is a good thing.)

What I'd like is the ability to move a tab into a different container. The "_Open Link in New Container Tab_" function is half of the solution, but it's slow and it does not close the existing tab. I'll speculate the meta context (e.g., container specific cookies) makes a simple move of a tab anything but simple. If that's the case, as a stop-gap maybe have "_Reopen Link in Other Container_". The key is to be tidy and close the current tab as part of the (re)open request.

Use cases:
* After a period of exploring a topic recognize there is a common theme in some of the open tabs. Want to create a new container and move the relevant tabs out of *Default* and into *Whatever*.
* A container has grown to the point where it has too many tabs in it, too many with diverse subjects. Need to create a new container and move some of the tabs into it.
* Two containers are found to be too specialized. Want to collapse them into a single one. Could be done with a _merge containers_ function but that seems too specialized. Efficiently moving tabs from one into the other is a more flexible solution.

**Comment by grahamperrin** [comment]
[Move tab from container or to container - Test Pilot / Containers - Mozilla Discourse](https://discourse.mozilla-community.org/t/move-tab-from-container-or-to-container/14134)

https://github.com/mozilla/testpilot-containers/issues/694 and https://github.com/mozilla/testpilot-containers/issues/562 were closed as duplicates of [Consider a tab context menu option to convert a normal tab to a container · Issue #311 · mozilla/testpilot-containers](https://github.com/mozilla/testpilot-containers/issues/311), which is also closed.

**Comment by jonathanKingston** [comment]
You probably want Context Plus extension. I'm going to close this also.

I have created a wiki page here:
https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers

I'm still open to suggestions if you think these issues are solvable without the privacy impact.

**Comment by jonathanKingston** [comment]
Also thanks for raising and the nice comments. I haven't had much time on this extension at the moment but I'm hoping we can start improving it soon.
