### ISSUE TITLE
option to seperate sidebar from bookmarks

### ISSUE THREAD

**Issue by Jan02** [jonathanKingston/sea-containers#48]
option to separate sea containers sidebar from bookmarks to show both bookmarks and sea containers

i.e. show bookmarks left and sea containers right

**Comment by jonathanKingston** [comment]
This isn't possible with this extension, if you need this I suggest filing a bug on Firefox itself: 
https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions%3A%20Frontend

Thanks
