### ISSUE TITLE
cannot drag and move/re-order open tabs inside the same container

### ISSUE THREAD

**Issue by ammarnajjar** [jonathanKingston/sea-containers#5]
- sea-container version 0.6
- Firefox version: 55.0a1 (2017-05-13) (64-bit)
- OS: Fedora release 25, Kernel: 4.10.14-200.fc25.x86_64

One cannot drag and move/re-order open tabs inside the same container.
I would provide debug info, but I don't know how, sorry.

**Comment by jonathanKingston** [comment]
Hey @ammarnajjar!

Ctrl+Alt+J should load up the browser console which should give a tonne of debugging.

Also about:debugging gives an extension specific view of that.

I have only tested dragging on Ubuntu, it's somewhat buggy in not permitting dragging to the first position etc.

**Comment by ammarnajjar** [comment]
Thanks @jonathanKingston  for the tip.
Hope that the following console output is enough:
 
```javascript
this[module] is undefined  nsBrowserGlue.js:174
	observe resource://app/components/nsBrowserGlue.js:174:9
	initializeWindow resource:///modules/sessionstore/SessionStore.jsm:1162:9
	onBeforeBrowserWindowShown/< resource:///modules/sessionstore/SessionStore.jsm:1307:9
	process resource://gre/modules/Promise-backend.js:922:23
	walkerLoop resource://gre/modules/Promise-backend.js:806:7
	bound walkerLoop self-hosted:944:17
	bound bound walkerLoop self-hosted:944:17
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode”  browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
Error in parsing value for ‘max-width’.  Declaration dropped.  browser.xul
Unknown property ‘enable-background’.  Declaration dropped.  sea-containers.svg
Property contained reference to invalid variable.  Error in parsing value for ‘background-image’.  Falling back to ‘initial’.  containers.css:91:1942
Unknown property ‘enable-background’.  Declaration dropped.  usercontext.svg
Unknown property ‘enable-background’.  Declaration dropped.  usercontext.svg
Unknown property ‘enable-background’.  Declaration dropped.  usercontext.svg
Unknown property ‘enable-background’.  Declaration dropped.  usercontext.svg
Property contained reference to invalid variable.  Error in parsing value for ‘fill’.  Falling back to ‘inherit’.  containers.css:96:2104
```

A screenshot can also be found [here](https://ibb.co/fdSMVk)

**Comment by jonathanKingston** [comment]
@ammarnajjar I don't think it is any of that. However I can confirm in refactoring the code I broke it for all platforms sorry. Working on it.

**Comment by jonathanKingston** [comment]
@ammarnajjar this will go out in the next release, I will likely be doing some follow up fixes for the other mentioned issues. Thanks for alerting me of that!
